### ISSUE TITLE
Spurious log message

### ISSUE THREAD

**Issue by pellepelster** [sam701/awstools#11]
After upgrading to 0.9.3 I get slightly irritating log messages, for example:

```
$ awstools assume ....
2016/09/30 08:50:30 Request body type has been overwritten. May cause race conditions
2016/09/30 08:50:30 Request body type has been overwritten. May cause race conditions
2016/09/30 08:50:30 Request body type has been overwritten. May cause race conditions
MFA token: xxxxxx
```

everything works fine, but the messages are a little bit worrying.

**Comment by sam701** [comment]
@pellepelster Could you provide your obfuscated `~/.config/awstools/config.toml`?

**Comment by pellepelster** [comment]
sure

```
defaultRegion = "eu-west-1"
defaultKmsKey = "arn:aws:kms:eu-west-1:$MAIN_ACCOUNT:key/$UUID

[profiles]
mainAccount = "$MAIN_ACCOUNT_NAME"
mainAccountMfaSession = "$MAIN_ACCOUNT_NAME_mfa"

[accounts]
$MAIN_ACCOUNT_NAME = "$MAIN_ACCOUNT"
account1 = "1234"
account2 = "1234"
account3 = "1234"
account4 = "1234"
account5 = "1234"
...
```

**Comment by sam701** [comment]
After an AWS SDK update, I get the same messages. It happens occasionally with `awstools assume` and `awstools ec2`. I tend to think it is an AWS SDK issue, since `awstools ec2` makes just as single AWS call `DescribeInstances`.

**Comment by sam701** [comment]
I didn't have this error message after updating the AWS-SDK.
