### ISSUE TITLE
DynamoDB utilities

### ISSUE THREAD

**Issue by deigote** [sam701/awstools#18]
I can think of:
- List tables
- Simple scan with _on the client_ filtering
- Ideally a way to query would be great, but I can imagine it to be way much more work.

**Comment by sam701** [comment]
Basic DDB operations (list, describe, get, scan) are implemented in version [`0.11.0`](https://github.com/sam701/awstools/releases/tag/0.11.0).

Please, describe other wishes in a separate issue 😄
