### ISSUE TITLE
Assume: Profile name needs quoting when updating `.aws/config`

### ISSUE THREAD

**Issue by ferdinand-beyer** [sam701/awstools#29]
After assuming a role, `awstools` updates the `.aws/config` file to set the default region. However, it does not quote the profile name which contains a space: `[profile <account> <role>]`.

We encountered this when using `credstash` which is based on AWS' `boto3` Python library. In the docs, it confirms that profile names need quoting:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configuration-file

Without quotes, the default region is not picked up.

The source seems to be:
https://github.com/sam701/awstools/blob/3799e52318b0b3bcd8c42b40a671a6badffdb81f/cred/cred.go#L25

**Comment by kelseymok** [comment]
Pull Request: https://github.com/sam701/awstools/pull/30

**Comment by sam701** [comment]
@ferdinand-beyer thanks for contribution
