### ISSUE TITLE
Support automatic key rotation

### ISSUE THREAD

**Issue by sam701** [sam701/awstools#3]
It can be an option in `config.toml` to rotate the key every `x` days.

**Comment by sam701** [comment]
I think now this is out of scope of this tool. The key rotation can be done by cron, anacron, etc. 💭

**Comment by moritzheiber** [comment]
I'm not sure, I like the functionality, especially since AWS does not provide this feature anywhere else. To me it sounds like it's complementing the feature set pretty well.

**Comment by sam701** [comment]
@moritzheiber That's true, AWS does not provide anything like this.

To keep the thing simple, there can be an option `rotateMasterKey` in `config.toml`, that is true by default. The master key will be then rotated before each role assumption.
