### ISSUE TITLE
Segmentation Fault 

### ISSUE THREAD

**Issue by olemaiwald** [sam701/awstools#33]
Machine: 
M1 MacBook Pro

Bash Version:
GNU bash, version 5.1.8(1)-release (aarch64-apple-darwin21.1.0)

For me, both, the homebrew installation binary throw segmentation faults whenever I try to use an awstools command.

**Comment by sam701** [comment]
The binary is compiled for intel processors. M1 chip is not yet supported by gitlab CI or github actions (Nov 2021). I can you compile `awstools` directly on your machine (`go build`).

**Comment by olemaiwald** [comment]
Works good this way, thank you!
