### ISSUE TITLE
Set default region for credential profiles that are created by awstools

### ISSUE THREAD

**Issue by moritzheiber** [sam701/awstools#7]
Currently, awstools has a setting for the default region it is operating in. However, this setting is not passed along to the AWS profile configuration when new credential profiles are added.

awstools should be adding this setting to `.aws/config` whenever it creates credential profiles in `.aws/credentials`.

**Comment by sam701** [comment]
@moritzheiber What are the consequences of not writing the `region` into `.aws/config`?

**Comment by moritzheiber** [comment]
Any application using the profile (i.e. "SharedCredentialsProvider") or even just the exported variables will fail because it's missing the region parameter. You'll either have to pass it to each application separately (`--region` for the cli) or add it to your profile yourself.

I'm just thinking, since we are having this configuration option anyway, why not append it to the profile we're creating anyway .. ?

**Comment by sam701** [comment]
Ok, it looks like a bug. I'll do it.
