### ISSUE TITLE
Release 0.9.0 is missing Darwin binaries

### ISSUE THREAD

**Issue by moritzheiber** [sam701/awstools#9]
For some reason the latest release is missing the Darwin binaries. How did you release it?

**Comment by sam701** [comment]
First, there was a build error because travis could not upload the artifacts. It was a problem on the github site. I just manually triggered the build again.

**Comment by moritzheiber** [comment]
We should investigate this once I'm back from Sri Lanka (no computer at hand). Might be a permission issue.

**Comment by sam701** [comment]
Cool, enjoy Sri Lanka! 😄 

There was `Skipping a deployment with the releases provider because this is not a tagged commit`. I didn't figure out how to force travis to deploy artifacts without a tagged commit. Of course, introducing a dummy commit and tagging it should work.

**Comment by moritzheiber** [comment]
Nice, looks like 0.9.0 not being pushed correctly was a hiccup between Travis and Github. Closing.
